name: docker-compose-actions-workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: |
          mkdir -p ~/.mytb-edge-data && sudo chown -R 799:799 ~/.mytb-edge-data
          mkdir -p ~/.mytb-edge-logs && sudo chown -R 799:799 ~/.mytb-edge-logs
          docker-compose up -d
          sleep 30s
          docker-compose logs
          docker run --network container:thingsboard-edge-postgres appropriate/curl -s --retry 10 --retry-connrefused http://localhost:5432/
          docker run --network container:thingsboard-edge appropriate/curl -s --retry 10 --retry-connrefused http://localhost:8080/
        env:
          CLOUD_ROUTING_KEY: ${{ secrets.CloudRoutingKey }}
          CLOUD_ROUTING_SECRET: ${{ secrets.CloudRoutingSecret }}
        shell: bash
