name: docker-compose-actions-workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
        env:
          CLOUD_ROUTING_KEY: ${{ secrets.CloudRoutingKey }}
          CLOUD_ROUTING_SECRET: ${{ secrets.CloudRoutingSecret }}
      - name: Sleep for 30 seconds
        run: sleep 30s
        shell: bash
      - name: Test
        run: docker run --network container:thingsboard-edge appropriate/curl -s --retry 10 --retry-connrefused http://localhost:8080/
